import { colors, fonts } from "@/constants";
import { StyleSheet } from "react-native";

export const passengerStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  searchBoxWrapper: {
    width: "100%",
    gap: 5,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  searchContainer: {
    position: "relative",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.borderLight,
    borderRadius: 35,
    padding: 20,
    maxHeight: 200,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    maxHeight: 200,
  },
  input: {
    borderColor: "#ddd",
    borderRadius: 5,
    paddingHorizontal: 10,
    backgroundColor: colors.borderLight,
    flex: 1,
    flexDirection: "row",
    fontFamily: fonts.primary,
    fontSize: 12,
    height: 50,
  },
  searchResults: {
    backgroundColor: "white",
    borderRadius: 5,
    maxHeight: 300,
  },
  mapSelectionButton: {
    padding: 12,
    backgroundColor: "#f0f0f0",
    borderRadius: 5,
    marginBottom: 5,
  },
  mapSelectionButtonText: {
    fontSize: 14,
    color: "#0066cc",
    textAlign: "center",
  },
  currentLocationBtn: {
    padding: 12,
    backgroundColor: "#e8e8e8",
    borderRadius: 5,
    marginBottom: 5,
  },
  currentLocationBtnText: {
    fontSize: 14,
    color: "#0066cc",
    textAlign: "center",
  },
  searchResultItem: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  searchResultText: {
    fontSize: 14,
    fontFamily: fonts.primary,
  },
  mapSelectionOverlay: {
    position: "absolute",
    top: 40,
    left: 10,
    right: 10,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    padding: 15,
    borderRadius: 5,
    alignItems: "center",
  },
  mapSelectionText: {
    color: "white",
    fontSize: 14,
    marginBottom: 10,
  },
  cancelButton: {
    backgroundColor: "#ff4444",
    padding: 8,
    borderRadius: 5,
    width: 100,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "white",
    fontSize: 14,
  },
  loader: {
    margin: 10,
  },
  requestButton: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: "#000",
    padding: 15,
    borderRadius: 5,
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  driverCard: {
    position: "absolute",
    bottom: 80,
    left: 20,
    right: 20,
    backgroundColor: "white",
    padding: 15,
    borderRadius: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  driverName: {
    fontSize: 18,
    fontWeight: "bold",
  },
  vehicleDetails: {
    fontSize: 14,
    color: "#666",
    marginTop: 5,
  },
  rideStatus: {
    fontSize: 14,
    color: "#666",
    marginTop: 5,
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderTopColor: "#eee",
  },
  suggestionText: {
    fontSize: 13,
    color: "#333",
    fontFamily: fonts.primary,
  },
  suggestionsContainer: {
    backgroundColor: colors.default,
    maxHeight: 200,
    marginTop: 5,
    borderRadius: 35,
    padding: 10,
  },
});
